;;;; src/conditions.lisp
;;;
;;; The error hierarchy (LOG-KIT-ERROR and its subclasses) plus the resource
;;; limits and the guards that raise them. Every other file signals through
;;; these, so this layer has no dependencies of its own.
(in-package #:log-kit)

(defun %write-condition-value (value stream)
  (typecase value
    ((or null number character string symbol) (write value :stream stream :escape t))
    (t (write-string "#<unprintable value>" stream))))

(defconstant +max-log-field-depth+ 64)
(defconstant +max-log-field-nodes+ 65536)
(defconstant +max-log-field-string-length+ 1048576)
(defconstant +max-log-field-array-elements+ 16384)

(define-condition log-kit-error (error) ()
  (:documentation "Base condition for every error this library itself signals."))

;;; INVALID-LOG-FIELDS and UNSUPPORTED-JSON-VALUE share the value/reason shape,
;;; but they are written out explicitly rather than generated by a macro on
;;; purpose: sb-cover credits the report lambdas below when a test prints one,
;;; whereas an equivalent macro body would run only at macroexpansion time and
;;; show up as permanently "not executed", regressing the coverage gate. Macros
;;; here are reserved for behavioral codegen (see DEFINE-LOG-LEVEL-MACROS,
;;; DEFHANDLE), not load-time definition forms.
(define-condition invalid-log-fields (log-kit-error)
  ((value :initarg :value :reader invalid-log-fields-value
          :documentation "The malformed field value or collection that was rejected.")
   (reason :initarg :reason :reader invalid-log-fields-reason
           :documentation "A human-readable string explaining why VALUE was rejected."))
  (:report (lambda (condition stream)
             (write-string "Invalid log fields " stream)
             (%write-condition-value (invalid-log-fields-value condition) stream)
             (format stream ": ~A" (invalid-log-fields-reason condition))))
  (:documentation "Signaled when a log call's fields cannot be validated: a
malformed plist, a non-symbol/non-string key, a duplicate canonical key, or
a JSON object/array member that fails its own shape check."))

;;; DEFINE-CONDITION's per-slot :DOCUMENTATION only reaches MOP slot
;;; introspection, not (DOCUMENTATION #'READER 'FUNCTION); set the latter
;;; explicitly so the reader generic functions answer DOCUMENTATION too.
(setf (documentation 'invalid-log-fields-value 'function)
      "The malformed field value or collection that was rejected.")
(setf (documentation 'invalid-log-fields-reason 'function)
      "A human-readable string explaining why VALUE was rejected.")

(define-condition unsupported-json-value (log-kit-error)
  ((value :initarg :value :reader unsupported-json-value-value
          :documentation "The value the JSON encoder could not represent.")
   (reason :initarg :reason :initform "unsupported value" :reader unsupported-json-value-reason
           :documentation "A human-readable string explaining why VALUE was rejected."))
  (:report (lambda (condition stream)
             (write-string "Unsupported JSON value " stream)
             (%write-condition-value (unsupported-json-value-value condition) stream)
             (format stream ": ~A" (unsupported-json-value-reason condition))))
  (:documentation "Signaled by the JSON handler when a field value has no
valid JSON representation: a non-finite float, a Unicode surrogate code
point in a string, or an object of a type the encoder does not support."))

(setf (documentation 'unsupported-json-value-value 'function)
      "The value the JSON encoder could not represent.")
(setf (documentation 'unsupported-json-value-reason 'function)
      "A human-readable string explaining why VALUE was rejected.")

(defun %proper-list-p (value)
  "True when VALUE is a finite, nil-terminated list. Uses Floyd's tortoise and
hare so a circular list is rejected in bounded time instead of looping forever."
  (loop with slow = value
        with fast = value
        do (cond
             ((null fast) (return t))
             ((atom fast) (return nil))
             ((null (cdr fast)) (return t))
             ((atom (cdr fast)) (return nil)))
           (setf slow (cdr slow)
                 fast (cddr fast))
           (when (eq slow fast)
             (return nil))))

(defun %invalid-fields (value reason)
  (error 'invalid-log-fields :value value :reason reason))

(define-condition log-resource-limit-exceeded (log-kit-error)
  ((resource :initarg :resource :reader log-resource-limit-resource
             :documentation "A keyword naming the bounded resource, e.g. :DEPTH,
:NODES, :STRING-LENGTH, or :ARRAY-ELEMENTS.")
   (limit :initarg :limit :reader log-resource-limit-limit
          :documentation "The configured maximum for RESOURCE.")
   (actual :initarg :actual :reader log-resource-limit-actual
           :documentation "The value that exceeded LIMIT."))
  (:report (lambda (condition stream)
             (format stream "Log field resource limit exceeded for ~A: limit ~D, observed ~D"
                     (log-resource-limit-resource condition)
                     (log-resource-limit-limit condition)
                     (log-resource-limit-actual condition))))
  (:documentation "Signaled when a field value's depth, node count, string
length, or collection size exceeds its configured bound, so a hostile or
accidentally huge value can never exhaust memory or loop unboundedly."))

(setf (documentation 'log-resource-limit-resource 'function)
      "A keyword naming the bounded resource, e.g. :DEPTH, :NODES,
:STRING-LENGTH, or :ARRAY-ELEMENTS.")
(setf (documentation 'log-resource-limit-limit 'function)
      "The configured maximum for RESOURCE.")
(setf (documentation 'log-resource-limit-actual 'function)
      "The value that exceeded LIMIT.")

(defun %resource-limit-exceeded (resource limit actual)
  (error 'log-resource-limit-exceeded :resource resource :limit limit :actual actual))

(defun %check-snapshot-size (resource actual limit)
  (when (> actual limit)
    (%resource-limit-exceeded resource limit actual)))

(defun %check-field-string-length (string)
  "Signal LOG-RESOURCE-LIMIT-EXCEEDED when STRING exceeds the field
string-length bound. The single place that bound is applied, so record,
logger, and snapshot code state the intent instead of repeating the resource
keyword and constant."
  (%check-snapshot-size :string-length (length string) +max-log-field-string-length+))

(defun %bounded-proper-list-length (value limit resource reason)
  "The length of VALUE, bounded by LIMIT and cycle-checked in one pass, so a
caller never has to fully traverse a hostile or circular list to reject it."
  (loop with tail = value
        with slow = value
        with fast = value
        for count from 0
        do (cond
             ((null tail) (return count))
             ((atom tail) (%invalid-fields value reason)))
           (when (= count limit)
             (%resource-limit-exceeded resource limit (1+ limit)))
           (setf tail (cdr tail))
           (if (and (consp fast) (consp (cdr fast)))
               (progn
                 (setf slow (cdr slow)
                       fast (cddr fast))
                 (when (eq slow fast)
                   (%invalid-fields value reason)))
               (setf fast nil))))

(defmacro check-types (&body clauses)
  "Run CHECK-TYPE on each (VALUE TYPE) pair in CLAUSES, in argument order,
so a constructor stating several CHECK-TYPE guards writes the value/type
table once instead of one CHECK-TYPE form per line."
  `(progn ,@(loop for (value type) in clauses collect `(check-type ,value ,type))))

(defun %constant-default (value)
  "Return VALUE unchanged. Used as a &KEY/&OPTIONAL default-value form in
place of a bare literal or DEFCONSTANT reference: SBCL constant-folds a
literal default at every call site that omits the keyword, so the source
position of the default form itself is never re-evaluated at runtime and
sb-cover reports it \"not executed\" even when the omitted-keyword path is
exercised. A default of (%CONSTANT-DEFAULT literal) is an ordinary,
non-inlined function call SBCL cannot fold away, so sb-cover credits it the
same way it credits any other executed form — the same tradeoff already
made project-wide when the DECLAIM INLINE on LEVEL</LEVEL<= was removed."
  value)
