;;;; src/conditions.lisp
;;;
;;; The error hierarchy: LOG-KIT-ERROR and its subclasses. Every other file
;;; signals through these, so this layer has no dependencies of its own.
;;; Resource-limit constants and guards live in limits.lisp; macro-authoring
;;; utilities (CHECK-TYPES, DEFUN-DEFAULTED, DEFMETHOD-DEFAULTED) live in
;;; macro-utils.lisp.
(in-package #:log-kit)

(defun %write-condition-value (value stream)
  (typecase value
    ((or null number character string symbol) (write value :stream stream :escape t))
    (t (write-string "#<unprintable value>" stream))))

(define-condition log-kit-error (error) ()
  (:documentation "Base condition for every error this library itself signals."))

;;; INVALID-LOG-FIELDS and UNSUPPORTED-JSON-VALUE share the value/reason shape,
;;; but they are written out explicitly rather than generated by a macro on
;;; purpose: sb-cover credits the report lambdas below when a test prints one,
;;; whereas an equivalent macro body would run only at macroexpansion time and
;;; show up as permanently "not executed", regressing the coverage gate. Macros
;;; here are reserved for behavioral codegen (see DEFINE-LOG-LEVEL-MACROS,
;;; DEFHANDLE), not load-time definition forms.
(define-condition invalid-log-fields (log-kit-error)
  ((value :initarg :value :reader invalid-log-fields-value
          :documentation "The malformed field value or collection that was rejected.")
   (reason :initarg :reason :reader invalid-log-fields-reason
           :documentation "A human-readable string explaining why VALUE was rejected."))
  (:report (lambda (condition stream)
             (write-string "Invalid log fields " stream)
             (%write-condition-value (invalid-log-fields-value condition) stream)
             (format stream ": ~A" (invalid-log-fields-reason condition))))
  (:documentation "Signaled when a log call's fields cannot be validated: a
malformed plist, a non-symbol/non-string key, a duplicate canonical key, or
a JSON object/array member that fails its own shape check."))

(document-readers
  (invalid-log-fields-value "The malformed field value or collection that was rejected.")
  (invalid-log-fields-reason "A human-readable string explaining why VALUE was rejected."))

(define-condition unsupported-json-value (log-kit-error)
  ((value :initarg :value :reader unsupported-json-value-value
          :documentation "The value the JSON encoder could not represent.")
   (reason :initarg :reason :initform "unsupported value" :reader unsupported-json-value-reason
           :documentation "A human-readable string explaining why VALUE was rejected."))
  (:report (lambda (condition stream)
             (write-string "Unsupported JSON value " stream)
             (%write-condition-value (unsupported-json-value-value condition) stream)
             (format stream ": ~A" (unsupported-json-value-reason condition))))
  (:documentation "Signaled by the JSON handler when a field value has no
valid JSON representation: a non-finite float, a Unicode surrogate code
point in a string, or an object of a type the encoder does not support."))

(document-readers
  (unsupported-json-value-value "The value the JSON encoder could not represent.")
  (unsupported-json-value-reason "A human-readable string explaining why VALUE was rejected."))

(defun %proper-list-p (value)
  "True when VALUE is a finite, nil-terminated list. Uses Floyd's tortoise and
hare so a circular list is rejected in bounded time instead of looping forever."
  (loop with slow = value
        with fast = value
        do (cond
             ((null fast) (return t))
             ((atom fast) (return nil))
             ((null (cdr fast)) (return t))
             ((atom (cdr fast)) (return nil)))
           (setf slow (cdr slow)
                 fast (cddr fast))
           (when (eq slow fast)
             (return nil))))

(defun %invalid-fields (value reason)
  (error 'invalid-log-fields :value value :reason reason))

(define-condition log-resource-limit-exceeded (log-kit-error)
  ((resource :initarg :resource :reader log-resource-limit-resource
             :documentation "A keyword naming the bounded resource, e.g. :DEPTH,
:NODES, :STRING-LENGTH, or :ARRAY-ELEMENTS.")
   (limit :initarg :limit :reader log-resource-limit-limit
          :documentation "The configured maximum for RESOURCE.")
   (actual :initarg :actual :reader log-resource-limit-actual
           :documentation "The value that exceeded LIMIT."))
  (:report (lambda (condition stream)
             (format stream "Log field resource limit exceeded for ~A: limit ~D, observed ~D"
                     (log-resource-limit-resource condition)
                     (log-resource-limit-limit condition)
                     (log-resource-limit-actual condition))))
  (:documentation "Signaled when a field value's depth, node count, string
length, or collection size exceeds its configured bound, so a hostile or
accidentally huge value can never exhaust memory or loop unboundedly."))

(document-readers
  (log-resource-limit-resource "A keyword naming the bounded resource, e.g. :DEPTH, :NODES,
:STRING-LENGTH, or :ARRAY-ELEMENTS.")
  (log-resource-limit-limit "The configured maximum for RESOURCE.")
  (log-resource-limit-actual "The value that exceeded LIMIT."))
