;;;; src/conditions.lisp
;;;
;;; The error hierarchy (LOG-KIT-ERROR and its subclasses) plus the resource
;;; limits and the guards that raise them. Every other file signals through
;;; these, so this layer has no dependencies of its own.
(in-package #:log-kit)

(defun %write-condition-value (value stream)
  (typecase value
    ((or null number character string symbol) (write value :stream stream :escape t))
    (t (write-string "#<unprintable value>" stream))))

(defconstant +max-log-field-depth+ 64)
(defconstant +max-log-field-nodes+ 65536)
(defconstant +max-log-field-string-length+ 1048576)
(defconstant +max-log-field-array-elements+ 16384)

(define-condition log-kit-error (error) ())

;;; INVALID-LOG-FIELDS and UNSUPPORTED-JSON-VALUE share the value/reason shape,
;;; but they are written out explicitly rather than generated by a macro on
;;; purpose: sb-cover credits the report lambdas below when a test prints one,
;;; whereas an equivalent macro body would run only at macroexpansion time and
;;; show up as permanently "not executed", regressing the coverage gate. Macros
;;; here are reserved for behavioral codegen (see DEFINE-LOG-LEVEL-MACROS,
;;; DEFHANDLE), not load-time definition forms.
(define-condition invalid-log-fields (log-kit-error)
  ((value :initarg :value :reader invalid-log-fields-value)
   (reason :initarg :reason :reader invalid-log-fields-reason))
  (:report (lambda (condition stream)
             (write-string "Invalid log fields " stream)
             (%write-condition-value (invalid-log-fields-value condition) stream)
             (format stream ": ~A" (invalid-log-fields-reason condition)))))

(define-condition unsupported-json-value (log-kit-error)
  ((value :initarg :value :reader unsupported-json-value-value)
   (reason :initarg :reason :initform "unsupported value" :reader unsupported-json-value-reason))
  (:report (lambda (condition stream)
             (write-string "Unsupported JSON value " stream)
             (%write-condition-value (unsupported-json-value-value condition) stream)
             (format stream ": ~A" (unsupported-json-value-reason condition)))))

(defun %proper-list-p (value)
  "True when VALUE is a finite, nil-terminated list. Uses Floyd's tortoise and
hare so a circular list is rejected in bounded time instead of looping forever."
  (loop with slow = value
        with fast = value
        do (cond
             ((null fast) (return t))
             ((atom fast) (return nil))
             ((null (cdr fast)) (return t))
             ((atom (cdr fast)) (return nil)))
           (setf slow (cdr slow)
                 fast (cddr fast))
           (when (eq slow fast)
             (return nil))))

(defun %invalid-fields (value reason)
  (error 'invalid-log-fields :value value :reason reason))

(define-condition log-resource-limit-exceeded (log-kit-error)
  ((resource :initarg :resource :reader log-resource-limit-resource)
   (limit :initarg :limit :reader log-resource-limit-limit)
   (actual :initarg :actual :reader log-resource-limit-actual))
  (:report (lambda (condition stream)
             (format stream "Log field resource limit exceeded for ~A: limit ~D, observed ~D"
                     (log-resource-limit-resource condition)
                     (log-resource-limit-limit condition)
                     (log-resource-limit-actual condition)))))

(defun %resource-limit-exceeded (resource limit actual)
  (error 'log-resource-limit-exceeded :resource resource :limit limit :actual actual))

(defun %check-snapshot-size (resource actual limit)
  (when (> actual limit)
    (%resource-limit-exceeded resource limit actual)))

(defun %check-field-string-length (string)
  "Signal LOG-RESOURCE-LIMIT-EXCEEDED when STRING exceeds the field
string-length bound. The single place that bound is applied, so record,
logger, and snapshot code state the intent instead of repeating the resource
keyword and constant."
  (%check-snapshot-size :string-length (length string) +max-log-field-string-length+))

(defun %bounded-proper-list-length (value limit resource reason)
  "The length of VALUE, bounded by LIMIT and cycle-checked in one pass, so a
caller never has to fully traverse a hostile or circular list to reject it."
  (loop with tail = value
        with slow = value
        with fast = value
        for count from 0
        do (cond
             ((null tail) (return count))
             ((atom tail) (%invalid-fields value reason)))
           (when (= count limit)
             (%resource-limit-exceeded resource limit (1+ limit)))
           (setf tail (cdr tail))
           (if (and (consp fast) (consp (cdr fast)))
               (progn
                 (setf slow (cdr slow)
                       fast (cddr fast))
                 (when (eq slow fast)
                   (%invalid-fields value reason)))
               (setf fast nil))))
