;;;; src/package.lisp
(defpackage #:log-kit
  (:use #:cl)
  (:shadow #:log)
  (:export
    #:+level-debug+
    #:+level-info+
    #:+level-warn+
    #:+level-error+
    #:+level-fatal+
    #:level-name
    #:level<
    #:level<=
    #:log-kit-error
    #:handler-lifecycle-error
    #:handler-lifecycle-error-handler
    #:handler-lifecycle-error-operation
    #:handler-lifecycle-error-state
    #:invalid-log-fields
    #:invalid-log-fields-value
    #:invalid-log-fields-reason
    #:unsupported-json-value
    #:unsupported-json-value-value
    #:unsupported-json-value-reason
    #:log-resource-limit-exceeded
    #:log-resource-limit-resource
    #:log-resource-limit-limit
    #:log-resource-limit-actual
    #:+json-null+
    #:+json-false+
    #:json-null-p
    #:json-false-p
    #:json-object
    #:json-object-p
    #:json-object-members
    #:json-array
    #:json-array-p
    #:json-array-elements
    #:log-record
    #:make-log-record
    #:log-record-level
    #:log-record-message
    #:log-record-timestamp
    #:log-record-fields
    #:log-record-logger-name
    #:handler
    #:handle-log-record
    #:flush-handler
    #:close-handler
    #:text-handler
    #:json-handler
    #:multi-handler
    #:filter-handler
    #:function-handler
    #:null-handler
    #:make-multi-handler
    #:make-filter-handler
    #:make-function-handler
    #:make-null-handler
    #:make-text-handler
    #:make-json-handler
    #:handler-open-p
    #:with-handler
    #:logger
    #:make-logger
    #:logger-with
    #:derive-logger
    #:logger-child
    #:logger-name
    #:logger-level
    #:logger-fields
    #:logger-clock
    #:logger-handler
    #:flush-logger
    #:*default-logger*
    #:set-default-logger
    #:with-default-logger
    #:with-log-context
    #:plist-to-alist
    #:log-enabled-p
    #:emit-log
    #:log-default
    #:log-debug
    #:log-info
    #:log-warn
    #:log-error
    #:log-fatal
    #:log-default-debug
    #:log-default-info
    #:log-default-warn
    #:log-default-error
    #:log-default-fatal
    #:condition-fields
    #:log-condition
    #:with-log-span))

(in-package #:log-kit)
